# Generated by Django 5.2 on 2026-01-23 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0024_balancesheet_cashflowstatement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("downloaded", "Downloaded"),
                            ("executed", "Executed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("long_orders", models.IntegerField(default=0)),
                ("short_orders", models.IntegerField(default=0)),
                (
                    "estimated_notional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(blank=True, null=True, upload_to="basket_orders/"),
                ),
                (
                    "excel_file",
                    models.FileField(blank=True, null=True, upload_to="basket_orders/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("strategy_type", models.CharField(max_length=50)),
                ("is_backtest", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2, default=1000000, max_digits=15
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "annualized_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BasketOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=10)),
                ("quantity", models.IntegerField()),
                ("target_weight", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "current_weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("last_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "estimated_notional",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("signal_reason", models.TextField(blank=True)),
                ("factor_scores", models.JSONField(blank=True, null=True)),
                (
                    "basket_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="strategies.basketorder",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
            options={
                "ordering": ["-estimated_notional"],
            },
        ),
        migrations.CreateModel(
            name="EquityLongShortPortfolio",
            fields=[
                (
                    "portfolio_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="strategies.portfolio",
                    ),
                ),
                (
                    "universe_type",
                    models.CharField(
                        choices=[
                            ("sp500", "S&P 500"),
                            ("russell1000", "Russell 1000"),
                            ("russell2000", "Russell 2000"),
                            ("custom", "Custom Universe"),
                        ],
                        default="sp500",
                        max_length=20,
                    ),
                ),
                (
                    "long_target_weight",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                (
                    "short_target_weight",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                (
                    "max_position_weight",
                    models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
                ),
                (
                    "rebalance_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("beta_neutral", models.BooleanField(default=True)),
                ("sector_neutral", models.BooleanField(default=True)),
                (
                    "max_leverage",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Equity Long-Short Portfolio",
                "verbose_name_plural": "Equity Long-Short Portfolios",
            },
            bases=("strategies.portfolio",),
        ),
        migrations.CreateModel(
            name="EquityUniverse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "min_market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("exclude_etfs", models.BooleanField(default=True)),
                ("exclude_adrs", models.BooleanField(default=True)),
                (
                    "stocks",
                    models.ManyToManyField(related_name="universes", to="stocks.stock"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StrategyParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameters", models.JSONField()),
                (
                    "portfolio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="strategies.portfolio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_type", models.CharField(max_length=10)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("trade_date", models.DateField()),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "signal_strength",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("strategy_reason", models.TextField(blank=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="strategies.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
            options={
                "ordering": ["-trade_date"],
            },
        ),
        migrations.AddField(
            model_name="basketorder",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_orders",
                to="strategies.equitylongshortportfolio",
            ),
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_return", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "annualized_return",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("sharpe_ratio", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "sortino_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("max_drawdown", models.DecimalField(decimal_places=4, max_digits=8)),
                ("volatility", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "beta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "alpha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "information_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("total_trades", models.IntegerField()),
                ("win_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "avg_trade_return",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                ("sector_exposures", models.JSONField(blank=True, null=True)),
                (
                    "portfolio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_result",
                        to="strategies.equitylongshortportfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest Result",
                "verbose_name_plural": "Backtest Results",
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("cash_balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("long_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("short_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "daily_return",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="strategies.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("portfolio", "date")},
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("entry_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("entry_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "market_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="strategies.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date"],
                "unique_together": {("portfolio", "stock", "entry_date")},
            },
        ),
        migrations.CreateModel(
            name="FactorScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_date", models.DateField()),
                (
                    "value_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "momentum_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "growth_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "composite_score",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                ("universe_rank", models.IntegerField()),
                ("decile", models.IntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factor_scores",
                        to="strategies.equitylongshortportfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-composite_score"],
                "unique_together": {("portfolio", "stock", "score_date")},
            },
        ),
    ]
