# Generated by Django 5.2 on 2026-01-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_incomestatement"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="incomestatement",
            new_name="stocks_inco_stock_i_078442_idx",
            old_name="stocks_inco_stock_i_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="incomestatement",
            new_name="stocks_inco_period__34b7fd_idx",
            old_name="stocks_inco_period__def456_idx",
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="earnings_per_share_basic",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="EPS basic",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="earnings_per_share_diluted",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="EPS diluted",
                max_digits=15,
                null=True,
            ),
        ),
    ]
