# Generated by Django 5.2 on 2026-01-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0023_add_unique_fiscal_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_end_date",
                    models.DateField(help_text="Period end date (YYYY-MM-DD)"),
                ),
                ("fiscal_year", models.IntegerField(db_index=True)),
                (
                    "fiscal_quarter",
                    models.IntegerField(
                        blank=True,
                        help_text="1-4 for quarterly, null for annual",
                        null=True,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        blank=True,
                        help_text="10-K, 10-Q, etc.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cash_and_cash_equivalents",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cash and cash equivalents (USD)",
                        null=True,
                    ),
                ),
                (
                    "short_term_investments",
                    models.BigIntegerField(
                        blank=True, help_text="Short-term investments (USD)", null=True
                    ),
                ),
                (
                    "accounts_receivable",
                    models.BigIntegerField(
                        blank=True, help_text="Accounts receivable (USD)", null=True
                    ),
                ),
                (
                    "inventory",
                    models.BigIntegerField(
                        blank=True, help_text="Inventory (USD)", null=True
                    ),
                ),
                (
                    "other_current_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Other current assets (USD)", null=True
                    ),
                ),
                (
                    "total_current_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Total current assets (USD)", null=True
                    ),
                ),
                (
                    "property_plant_equipment",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Property, plant and equipment (USD)",
                        null=True,
                    ),
                ),
                (
                    "goodwill",
                    models.BigIntegerField(
                        blank=True, help_text="Goodwill (USD)", null=True
                    ),
                ),
                (
                    "intangible_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Intangible assets (USD)", null=True
                    ),
                ),
                (
                    "long_term_investments",
                    models.BigIntegerField(
                        blank=True, help_text="Long-term investments (USD)", null=True
                    ),
                ),
                (
                    "other_non_current_assets",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Other non-current assets (USD)",
                        null=True,
                    ),
                ),
                (
                    "total_non_current_assets",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total non-current assets (USD)",
                        null=True,
                    ),
                ),
                (
                    "total_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Total assets (USD)", null=True
                    ),
                ),
                (
                    "accounts_payable",
                    models.BigIntegerField(
                        blank=True, help_text="Accounts payable (USD)", null=True
                    ),
                ),
                (
                    "short_term_debt",
                    models.BigIntegerField(
                        blank=True, help_text="Short-term debt (USD)", null=True
                    ),
                ),
                (
                    "other_current_liabilities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Other current liabilities (USD)",
                        null=True,
                    ),
                ),
                (
                    "total_current_liabilities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total current liabilities (USD)",
                        null=True,
                    ),
                ),
                (
                    "long_term_debt",
                    models.BigIntegerField(
                        blank=True, help_text="Long-term debt (USD)", null=True
                    ),
                ),
                (
                    "other_non_current_liabilities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Other non-current liabilities (USD)",
                        null=True,
                    ),
                ),
                (
                    "total_non_current_liabilities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total non-current liabilities (USD)",
                        null=True,
                    ),
                ),
                (
                    "total_liabilities",
                    models.BigIntegerField(
                        blank=True, help_text="Total liabilities (USD)", null=True
                    ),
                ),
                (
                    "common_stock",
                    models.BigIntegerField(
                        blank=True, help_text="Common stock (USD)", null=True
                    ),
                ),
                (
                    "retained_earnings",
                    models.BigIntegerField(
                        blank=True, help_text="Retained earnings (USD)", null=True
                    ),
                ),
                (
                    "additional_paid_in_capital",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Additional paid-in capital (USD)",
                        null=True,
                    ),
                ),
                (
                    "other_equity",
                    models.BigIntegerField(
                        blank=True, help_text="Other equity (USD)", null=True
                    ),
                ),
                (
                    "total_equity",
                    models.BigIntegerField(
                        blank=True, help_text="Total equity (USD)", null=True
                    ),
                ),
                (
                    "total_liabilities_and_equity",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total liabilities and equity (USD)",
                        null=True,
                    ),
                ),
                (
                    "filing_date",
                    models.DateField(
                        blank=True, help_text="SEC filing date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Balance Sheet",
                "verbose_name_plural": "Balance Sheets",
                "ordering": [
                    "stock",
                    "-fiscal_year",
                    "-fiscal_quarter",
                    "-period_end_date",
                ],
            },
        ),
        migrations.CreateModel(
            name="CashFlowStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_end_date",
                    models.DateField(help_text="Period end date (YYYY-MM-DD)"),
                ),
                ("fiscal_year", models.IntegerField(db_index=True)),
                (
                    "fiscal_quarter",
                    models.IntegerField(
                        blank=True,
                        help_text="1-4 for quarterly, null for annual",
                        null=True,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        blank=True,
                        help_text="10-K, 10-Q, etc.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "net_income",
                    models.BigIntegerField(
                        blank=True, help_text="Net income (USD)", null=True
                    ),
                ),
                (
                    "depreciation_amortization",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Depreciation and amortization (USD)",
                        null=True,
                    ),
                ),
                (
                    "accounts_receivable_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Change in accounts receivable (USD)",
                        null=True,
                    ),
                ),
                (
                    "inventory_change",
                    models.BigIntegerField(
                        blank=True, help_text="Change in inventory (USD)", null=True
                    ),
                ),
                (
                    "accounts_payable_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Change in accounts payable (USD)",
                        null=True,
                    ),
                ),
                (
                    "other_working_capital_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Other working capital changes (USD)",
                        null=True,
                    ),
                ),
                (
                    "other_non_cash_items",
                    models.BigIntegerField(
                        blank=True, help_text="Other non-cash items (USD)", null=True
                    ),
                ),
                (
                    "net_cash_from_operating_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Net cash from operating activities (USD)",
                        null=True,
                    ),
                ),
                (
                    "capital_expenditures",
                    models.BigIntegerField(
                        blank=True, help_text="Capital expenditures (USD)", null=True
                    ),
                ),
                (
                    "acquisitions",
                    models.BigIntegerField(
                        blank=True, help_text="Acquisitions, net (USD)", null=True
                    ),
                ),
                (
                    "investments_purchased",
                    models.BigIntegerField(
                        blank=True, help_text="Investments purchased (USD)", null=True
                    ),
                ),
                (
                    "investments_sold",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Investments sold/matured (USD)",
                        null=True,
                    ),
                ),
                (
                    "other_investing_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Other investing activities (USD)",
                        null=True,
                    ),
                ),
                (
                    "net_cash_from_investing_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Net cash from investing activities (USD)",
                        null=True,
                    ),
                ),
                (
                    "debt_issued",
                    models.BigIntegerField(
                        blank=True, help_text="Debt issued (USD)", null=True
                    ),
                ),
                (
                    "debt_repayment",
                    models.BigIntegerField(
                        blank=True, help_text="Debt repayment (USD)", null=True
                    ),
                ),
                (
                    "common_stock_issued",
                    models.BigIntegerField(
                        blank=True, help_text="Common stock issued (USD)", null=True
                    ),
                ),
                (
                    "common_stock_repurchased",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Common stock repurchased (USD)",
                        null=True,
                    ),
                ),
                (
                    "dividends_paid",
                    models.BigIntegerField(
                        blank=True, help_text="Dividends paid (USD)", null=True
                    ),
                ),
                (
                    "other_financing_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Other financing activities (USD)",
                        null=True,
                    ),
                ),
                (
                    "net_cash_from_financing_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Net cash from financing activities (USD)",
                        null=True,
                    ),
                ),
                (
                    "net_change_in_cash",
                    models.BigIntegerField(
                        blank=True, help_text="Net change in cash (USD)", null=True
                    ),
                ),
                (
                    "cash_at_beginning_of_period",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cash at beginning of period (USD)",
                        null=True,
                    ),
                ),
                (
                    "cash_at_end_of_period",
                    models.BigIntegerField(
                        blank=True, help_text="Cash at end of period (USD)", null=True
                    ),
                ),
                (
                    "filing_date",
                    models.DateField(
                        blank=True, help_text="SEC filing date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cash Flow Statement",
                "verbose_name_plural": "Cash Flow Statements",
                "ordering": [
                    "stock",
                    "-fiscal_year",
                    "-fiscal_quarter",
                    "-period_end_date",
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="incomestatement",
            name="unique_fiscal_period",
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_sheets",
                to="stocks.stock",
            ),
        ),
        migrations.AddField(
            model_name="cashflowstatement",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_flow_statements",
                to="stocks.stock",
            ),
        ),
        migrations.AddIndex(
            model_name="balancesheet",
            index=models.Index(
                fields=["stock", "-fiscal_year", "-fiscal_quarter"],
                name="stocks_bala_stock_i_fdb1dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="balancesheet",
            index=models.Index(
                fields=["period_end_date"], name="stocks_bala_period__d68a44_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balancesheet",
            unique_together={
                ("stock", "period_end_date", "fiscal_year", "fiscal_quarter")
            },
        ),
        migrations.AddIndex(
            model_name="cashflowstatement",
            index=models.Index(
                fields=["stock", "-fiscal_year", "-fiscal_quarter"],
                name="stocks_cash_stock_i_ed5b4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowstatement",
            index=models.Index(
                fields=["period_end_date"], name="stocks_cash_period__9efa02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cashflowstatement",
            unique_together={
                ("stock", "period_end_date", "fiscal_year", "fiscal_quarter")
            },
        ),
    ]
