# Generated by Django 5.2 on 2026-01-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0024_balancesheet_cashflowstatement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Trading date (YYYY-MM-DD)")),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Opening price",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Highest price",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Lowest price",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Closing price",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "adjusted_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Adjusted closing price",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, help_text="Trading volume", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Price Data",
                "verbose_name_plural": "Daily Price Data",
                "ordering": ["stock", "-date"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-date"], name="stocks_dail_stock_i_3e52ef_idx"
                    ),
                    models.Index(fields=["date"], name="stocks_dail_date_8331a4_idx"),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
